
language: node_js

node_js:
  - 0.10.30
    
before_script:

after_success:
  - echo $TOTO
  - git remote -v
  - git config --global user.email "[ama.310@hotmail.com]"
  - git config --global user.name "[ama4447]"
  - git checkout master
  - npm version patch
  - git commit -am "[skip ci] bump version"
  - git log --oneline
  - git remote set-url origin [https://github.com/ama4447/travis]
  - git push origin master
